### ISSUE TITLE
打扰你了！！评分是多少

### ISSUE THREAD

**Issue by 123moon** [samxuxiang/Attention-Based-Hierarchical-Model-#1]
评分是多少吖？？？？

**Comment by yuewuqing2224** [comment]
You can refer to our paper at: https://samxuxiang.github.io/research.html. 
Note that I am no longer maintaining this code and part of the experiments are conducted by my teammates.

**Comment by samxuxiang** [comment]
You can refer to our paper at: https://samxuxiang.github.io/research.html.
Note that I am no longer maintaining this code and part of the experiments are conducted by my teammates.
